-- Load all configuration modules
require('config.options')
require('config.autocmds')
require('config.keymaps')

require('plugins.mason')
require('plugins.tokyonight')
require('plugins.mini')
require('plugins.neo-tree')
require('plugins.blink')
require('plugins.misc')
require('plugins.trouble')
require('plugins.which-key')
require('plugins.lua-line')
require('plugins.render-markdown')
