-- Load all plugins
require("plugins.mason")
require("plugins.tokyonight")
require("plugins.mini")
require("plugins.neo-tree")
require("plugins.blink")
require("plugins.rustacean")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.trouble")
require("plugins.which-key")
require("plugins.lua-line")
require("plugins.render-markdown")
require("plugins.toggleterm")
